#
##????
#main ? java
#- controller
#- service
#
#resources
#- mapper
#- static -> ?????
#- resources
#- template
#-
#
#spring? ????? ? ????? ? ?????
#??? ? ????? spring? ????.
#
#/? ?? spring? ?? ?? ??? ???
#
#Account? ??
#???? properties ??? ????? ???.
#.yml ?? .yaml ? ?
# JPA? ??? ?? Mybatis ???.
#hibernate? ?? ??? ????? ????.
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.spring_project_test_24_01_11: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
#  ??? ?? ?????? ??
  datasource:
    url: jdbc:mysql://www.adapter-gwangalli.com:3306/sceunho
    username: root
    password: ivill0080@
    driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa ??? yaml? ???
  jpa:
    defer-datasource-initialization: true
#    create? spring ???? ??? ?? ??? ?? ??
    #update ? ??? ??? ?? ??
    hibernate.ddl-auto: create
    show-sql: true
    properties:
#      sql? ??? ?????
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
sql.init.mode: always
springdoc:
#  swagger? api ??? ?????? ??? ??
  swagger-ui:
#    tag? operation ??? ?????
    operations-sorter: alpha
    tags-sorter: alpha
